
/**
* CRUD service for BookingRateSnapshot
* This file was auto-generated by a script. Do not modify it manually.
*/
import prisma from '@/clients/prisma';
import { Prisma } from '@prisma/client';

// Type Aliases
type BookingRateSnapshotCreateInput = Prisma.BookingRateSnapshotCreateInput;
type BookingRateSnapshotUpdateInput = Prisma.BookingRateSnapshotUpdateInput;

// Create BookingRateSnapshot
export const createBookingRateSnapshot = async (data: BookingRateSnapshotCreateInput) => {
  return prisma.bookingRateSnapshot.create({
    data,
  });
};

// Get BookingRateSnapshot by ID
export const getBookingRateSnapshotById = async (id: string) => {
  return prisma.bookingRateSnapshot.findUnique({
    where: { id },
  });
};

// List BookingRateSnapshots
export const listBookingRateSnapshots = async (filter: any = {}) => {
  return prisma.bookingRateSnapshot.findMany({
    where: filter,
    orderBy: { createdAt: 'desc' },
  });
};

// Update BookingRateSnapshot
export const updateBookingRateSnapshot = async (id: string, data: BookingRateSnapshotUpdateInput) => {
  return prisma.bookingRateSnapshot.update({
    where: { id },
    data,
  });
};

// Delete BookingRateSnapshot
export const deleteBookingRateSnapshot = async (id: string) => {
  return prisma.bookingRateSnapshot.delete({
    where: { id },
  });
};
