
/**
* CRUD service for BookingTemplate
* This file was auto-generated by a script. Do not modify it manually.
*/
import prisma from '@/clients/prisma';
import { Prisma } from '@prisma/client';

// Type Aliases
type BookingTemplateCreateInput = Prisma.BookingTemplateCreateInput;
type BookingTemplateUpdateInput = Prisma.BookingTemplateUpdateInput;

// Create BookingTemplate
export const createBookingTemplate = async (data: BookingTemplateCreateInput) => {
  return prisma.bookingTemplate.create({
    data,
  });
};

// Get BookingTemplate by ID
export const getBookingTemplateById = async (id: string) => {
  return prisma.bookingTemplate.findUnique({
    where: { id },
  });
};

// List BookingTemplates
export const listBookingTemplates = async (filter: any = {}) => {
  return prisma.bookingTemplate.findMany({
    where: filter,
    orderBy: { createdAt: 'desc' },
  });
};

// Update BookingTemplate
export const updateBookingTemplate = async (id: string, data: BookingTemplateUpdateInput) => {
  return prisma.bookingTemplate.update({
    where: { id },
    data,
  });
};

// Delete BookingTemplate
export const deleteBookingTemplate = async (id: string) => {
  return prisma.bookingTemplate.delete({
    where: { id },
  });
};
