
/**
* CRUD service for BookingAction
* This file was auto-generated by a script. Do not modify it manually.
*/
import prisma from '@/clients/prisma';
import { Prisma } from '@prisma/client';

// Type Aliases
type BookingActionCreateInput = Prisma.BookingActionCreateInput;
type BookingActionUpdateInput = Prisma.BookingActionUpdateInput;

// Create BookingAction
export const createBookingAction = async (data: BookingActionCreateInput) => {
  return prisma.bookingAction.create({
    data,
  });
};

// Get BookingAction by ID
export const getBookingActionById = async (id: string) => {
  return prisma.bookingAction.findUnique({
    where: { id },
  });
};

// List BookingActions
export const listBookingActions = async (filter: any = {}) => {
  return prisma.bookingAction.findMany({
    where: filter,
    orderBy: { createdAt: 'desc' },
  });
};

// Update BookingAction
export const updateBookingAction = async (id: string, data: BookingActionUpdateInput) => {
  return prisma.bookingAction.update({
    where: { id },
    data,
  });
};

// Delete BookingAction
export const deleteBookingAction = async (id: string) => {
  return prisma.bookingAction.delete({
    where: { id },
  });
};
