
/**
* CRUD service for BookingItem
* This file was auto-generated by a script. Do not modify it manually.
*/
import prisma from '@/clients/prisma';
import { Prisma } from '@prisma/client';

// Type Aliases
type BookingItemCreateInput = Prisma.BookingItemCreateInput;
type BookingItemUpdateInput = Prisma.BookingItemUpdateInput;

// Create BookingItem
export const createBookingItem = async (data: BookingItemCreateInput) => {
  return prisma.bookingItem.create({
    data,
  });
};

// Get BookingItem by ID
export const getBookingItemById = async (id: string) => {
  return prisma.bookingItem.findUnique({
    where: { id },
  });
};

// List BookingItems
export const listBookingItems = async (filter: any = {}) => {
  return prisma.bookingItem.findMany({
    where: filter,
    orderBy: { createdAt: 'desc' },
  });
};

// Update BookingItem
export const updateBookingItem = async (id: string, data: BookingItemUpdateInput) => {
  return prisma.bookingItem.update({
    where: { id },
    data,
  });
};

// Delete BookingItem
export const deleteBookingItem = async (id: string) => {
  return prisma.bookingItem.delete({
    where: { id },
  });
};
