
/**
* CRUD service for BookingItemAddOn
* This file was auto-generated by a script. Do not modify it manually.
*/
import prisma from '@/clients/prisma';
import { Prisma } from '@prisma/client';

// Type Aliases
type BookingItemAddOnCreateInput = Prisma.BookingItemAddOnCreateInput;
type BookingItemAddOnUpdateInput = Prisma.BookingItemAddOnUpdateInput;

// Create BookingItemAddOn
export const createBookingItemAddOn = async (data: BookingItemAddOnCreateInput) => {
  return prisma.bookingItemAddOn.create({
    data,
  });
};

// Get BookingItemAddOn by ID
export const getBookingItemAddOnById = async (id: string) => {
  return prisma.bookingItemAddOn.findUnique({
    where: { id },
  });
};

// List BookingItemAddOns
export const listBookingItemAddOns = async (filter: any = {}) => {
  return prisma.bookingItemAddOn.findMany({
    where: filter,
    orderBy: { createdAt: 'desc' },
  });
};

// Update BookingItemAddOn
export const updateBookingItemAddOn = async (id: string, data: BookingItemAddOnUpdateInput) => {
  return prisma.bookingItemAddOn.update({
    where: { id },
    data,
  });
};

// Delete BookingItemAddOn
export const deleteBookingItemAddOn = async (id: string) => {
  return prisma.bookingItemAddOn.delete({
    where: { id },
  });
};
