
/**
* CRUD service for BookingRequestActionValue
* This file was auto-generated by a script. Do not modify it manually.
*/
import prisma from '@/clients/prisma';
import { Prisma } from '@prisma/client';

// Type Aliases
type BookingRequestActionValueCreateInput = Prisma.BookingRequestActionValueCreateInput;
type BookingRequestActionValueUpdateInput = Prisma.BookingRequestActionValueUpdateInput;

// Create BookingRequestActionValue
export const createBookingRequestActionValue = async (data: BookingRequestActionValueCreateInput) => {
  return prisma.bookingRequestActionValue.create({
    data,
  });
};

// Get BookingRequestActionValue by ID
export const getBookingRequestActionValueById = async (id: string) => {
  return prisma.bookingRequestActionValue.findUnique({
    where: { id },
  });
};

// List BookingRequestActionValues
export const listBookingRequestActionValues = async (filter: any = {}) => {
  return prisma.bookingRequestActionValue.findMany({
    where: filter,
    orderBy: { createdAt: 'desc' },
  });
};

// Update BookingRequestActionValue
export const updateBookingRequestActionValue = async (id: string, data: BookingRequestActionValueUpdateInput) => {
  return prisma.bookingRequestActionValue.update({
    where: { id },
    data,
  });
};

// Delete BookingRequestActionValue
export const deleteBookingRequestActionValue = async (id: string) => {
  return prisma.bookingRequestActionValue.delete({
    where: { id },
  });
};
