
/**
* CRUD service for CancellationRequest
* This file was auto-generated by a script. Do not modify it manually.
*/
import prisma from '@/clients/prisma';
import { Prisma } from '@prisma/client';

// Type Aliases
type CancellationRequestCreateInput = Prisma.CancellationRequestCreateInput;
type CancellationRequestUpdateInput = Prisma.CancellationRequestUpdateInput;

// Create CancellationRequest
export const createCancellationRequest = async (data: CancellationRequestCreateInput) => {
  return prisma.cancellationRequest.create({
    data,
  });
};

// Get CancellationRequest by ID
export const getCancellationRequestById = async (id: string) => {
  return prisma.cancellationRequest.findUnique({
    where: { id },
  });
};

// List CancellationRequests
export const listCancellationRequests = async (filter: any = {}) => {
  return prisma.cancellationRequest.findMany({
    where: filter,
    orderBy: { createdAt: 'desc' },
  });
};

// Update CancellationRequest
export const updateCancellationRequest = async (id: string, data: CancellationRequestUpdateInput) => {
  return prisma.cancellationRequest.update({
    where: { id },
    data,
  });
};

// Delete CancellationRequest
export const deleteCancellationRequest = async (id: string) => {
  return prisma.cancellationRequest.delete({
    where: { id },
  });
};
