
/**
* CRUD service for CancellationPolicy
* This file was auto-generated by a script. Do not modify it manually.
*/
import prisma from '@/clients/prisma';
import { Prisma } from '@prisma/client';

// Type Aliases
type CancellationPolicyCreateInput = Prisma.CancellationPolicyCreateInput;
type CancellationPolicyUpdateInput = Prisma.CancellationPolicyUpdateInput;

// Create CancellationPolicy
export const createCancellationPolicy = async (data: CancellationPolicyCreateInput) => {
  return prisma.cancellationPolicy.create({
    data,
  });
};

// Get CancellationPolicy by ID
export const getCancellationPolicyById = async (id: string) => {
  return prisma.cancellationPolicy.findUnique({
    where: { id },
  });
};

// List CancellationPolicys
export const listCancellationPolicys = async (filter: any = {}) => {
  return prisma.cancellationPolicy.findMany({
    where: filter,
    orderBy: { createdAt: 'desc' },
  });
};

// Update CancellationPolicy
export const updateCancellationPolicy = async (id: string, data: CancellationPolicyUpdateInput) => {
  return prisma.cancellationPolicy.update({
    where: { id },
    data,
  });
};

// Delete CancellationPolicy
export const deleteCancellationPolicy = async (id: string) => {
  return prisma.cancellationPolicy.delete({
    where: { id },
  });
};
