
/**
* CRUD service for InvoicePayment
* This file was auto-generated by a script. Do not modify it manually.
*/
import prisma from '@/clients/prisma';
import { Prisma } from '@prisma/client';

// Type Aliases
type InvoicePaymentCreateInput = Prisma.InvoicePaymentCreateInput;
type InvoicePaymentUpdateInput = Prisma.InvoicePaymentUpdateInput;

// Create InvoicePayment
export const createInvoicePayment = async (data: InvoicePaymentCreateInput) => {
  return prisma.invoicePayment.create({
    data,
  });
};

// Get InvoicePayment by ID
export const getInvoicePaymentById = async (id: string) => {
  return prisma.invoicePayment.findUnique({
    where: { id },
  });
};

// List InvoicePayments
export const listInvoicePayments = async (filter: any = {}) => {
  return prisma.invoicePayment.findMany({
    where: filter,
    orderBy: { createdAt: 'desc' },
  });
};

// Update InvoicePayment
export const updateInvoicePayment = async (id: string, data: InvoicePaymentUpdateInput) => {
  return prisma.invoicePayment.update({
    where: { id },
    data,
  });
};

// Delete InvoicePayment
export const deleteInvoicePayment = async (id: string) => {
  return prisma.invoicePayment.delete({
    where: { id },
  });
};
