
/**
* CRUD service for RateAddOn
* This file was auto-generated by a script. Do not modify it manually.
*/
import prisma from '@/clients/prisma';
import { Prisma } from '@prisma/client';

// Type Aliases
type RateAddOnCreateInput = Prisma.RateAddOnCreateInput;
type RateAddOnUpdateInput = Prisma.RateAddOnUpdateInput;

// Create RateAddOn
export const createRateAddOn = async (data: RateAddOnCreateInput) => {
  return prisma.rateAddOn.create({
    data,
  });
};

// Get RateAddOn by ID
export const getRateAddOnById = async (id: string) => {
  return prisma.rateAddOn.findUnique({
    where: { id },
  });
};

// List RateAddOns
export const listRateAddOns = async (filter: any = {}) => {
  return prisma.rateAddOn.findMany({
    where: filter,
    orderBy: { createdAt: 'desc' },
  });
};

// Update RateAddOn
export const updateRateAddOn = async (id: string, data: RateAddOnUpdateInput) => {
  return prisma.rateAddOn.update({
    where: { id },
    data,
  });
};

// Delete RateAddOn
export const deleteRateAddOn = async (id: string) => {
  return prisma.rateAddOn.delete({
    where: { id },
  });
};
