
/**
* CRUD service for ResourceAsset
* This file was auto-generated by a script. Do not modify it manually.
*/
import prisma from '@/clients/prisma';
import { Prisma } from '@prisma/client';

// Type Aliases
type ResourceAssetCreateInput = Prisma.ResourceAssetCreateInput;
type ResourceAssetUpdateInput = Prisma.ResourceAssetUpdateInput;

// Create ResourceAsset
export const createResourceAsset = async (data: ResourceAssetCreateInput) => {
  return prisma.resourceAsset.create({
    data,
  });
};

// Get ResourceAsset by ID
export const getResourceAssetById = async (id: string) => {
  return prisma.resourceAsset.findUnique({
    where: { id },
  });
};

// List ResourceAssets
export const listResourceAssets = async (filter: any = {}) => {
  return prisma.resourceAsset.findMany({
    where: filter,
    orderBy: { createdAt: 'desc' },
  });
};

// Update ResourceAsset
export const updateResourceAsset = async (id: string, data: ResourceAssetUpdateInput) => {
  return prisma.resourceAsset.update({
    where: { id },
    data,
  });
};

// Delete ResourceAsset
export const deleteResourceAsset = async (id: string) => {
  return prisma.resourceAsset.delete({
    where: { id },
  });
};
