
/**
* CRUD service for UiTemplate
* This file was auto-generated by a script. Do not modify it manually.
*/
import prisma from '@/clients/prisma';
import { Prisma } from '@prisma/client';

// Type Aliases
type UiTemplateCreateInput = Prisma.UiTemplateCreateInput;
type UiTemplateUpdateInput = Prisma.UiTemplateUpdateInput;

// Create UiTemplate
export const createUiTemplate = async (data: UiTemplateCreateInput) => {
  return prisma.uiTemplate.create({
    data,
  });
};

// Get UiTemplate by ID
export const getUiTemplateById = async (id: string) => {
  return prisma.uiTemplate.findUnique({
    where: { id },
  });
};

// List UiTemplates
export const listUiTemplates = async (filter: any = {}) => {
  return prisma.uiTemplate.findMany({
    where: filter,
    orderBy: { createdAt: 'desc' },
  });
};

// Update UiTemplate
export const updateUiTemplate = async (id: string, data: UiTemplateUpdateInput) => {
  return prisma.uiTemplate.update({
    where: { id },
    data,
  });
};

// Delete UiTemplate
export const deleteUiTemplate = async (id: string) => {
  return prisma.uiTemplate.delete({
    where: { id },
  });
};
